version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/development.Dockerfile
    env_file: docker/.env
    ports:
      - 3000:3000
    # mount source volume, but
    # don't overwrite `node_modules` or mirror dir from container
    volumes:
      - ./public:/usr/src/public
      - ./bin:/usr/src/bin
      - ./config:/usr/src/config
      - ./lib:/usr/src/lib
      - ./migrations:/usr/src/migrations
      - ./test:/usr/src/test
    depends_on:
      - mongo
    tty: true

  mongo:
    image: mongo:3.2
    ports:
      - 27017:27017
    # Optionally mount external data directory
    volumes:
      - ./tmp/db:/data/db
