# version 1.0
name: Build and push
on:
  push:
    tags:
      - '*'

jobs:
  work:
    name: Work
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Lowercase
        id: lower
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build & Push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ steps.lower.outputs.lowercase }}
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Trigger stack update
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.STACK_URL }}
          method: 'POST'
          customHeaders: '{"Accept":  "application/vnd.github.everest-preview+json"}'
          bearerToken: ${{ secrets.REGISTRY_PASSWORD }}
          data: '{"event_type": "update-stack"}'
      - name: Notify Slack
        uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
