name: Docker Image CI

on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ext/*'
      - 'lib/*'
      - 'bin/*'
      - 'Dockerfile'
      - 'package.json'
      - 'gulpfile.js'
      - 'index.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
